apiVersion: apps/v1
kind: Deployment
metadata:
  name: rephraser-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rephraser-api
  template:
    metadata:
      labels:
        app: rephraser-api
    spec:
      containers:
        - name: rephraser-api-container
          image: gcr.io/rephraser-api-repo/rephraser-api-image:latest
          ports:
            - containerPort: 8000
