apiVersion: v1
kind: Service
metadata:
  name: rephraser-api-service
spec:
  selector:
    app: rephraser-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer  
