name: Build and Deploy 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.12
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: |
        make install
    - name: Test
      run: |
        make test
    - name: Build
      run: |
        make build
    - name: Deploy 
      run: |
        #make deploy
